export const CALCULATER_LIST = [
    { name: "1", label: "1" },
    { name: "2", label: "2" },
    { name: "3", label: "3" },
    { name: "+", label: "+" },
    { name: "4", label: "4" },
    { name: "5", label: "5" },
    { name: "6", label: "6" },
    { name: "-", label: "-" },
    { name: "7", label: "7" },
    { name: "8", label: "8" },
    { name: "9", label: "9" },
    { name: "*", label: "*" },
    { name: "0", label: "0" },
    { name: "/", label: "/" },
    { name: "C", label: "C", isClear: true },
    { name: "=", label: "=", isCalculate: true },
];